version: '3'
services:
  js_and_ts:
    container_name: js_and_ts
    build: .
    tty: true
    expose:
      - 80
    volumes:
      - type: bind
        source: .
        target: /home/developer/src
