name: MyPage Build Test
on:
  push:
    branches:
      - "!main"
jobs:
  test-for-buildability:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          repository: "kikugawa-shoma/learning-sandbox"
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: actions/cache@v3
        id: npm_cache
        with:
          path: myPage/node_modules
          key: ${{ hashFiles('myPage/package-lock.json') }}
      - name: Install NPM Modules
        if: steps.npm_cache.outputs.cache-hit != 'true'
        working-directory: myPage
        run: npm ci
      - name: Build Check
        working-directory: myPage
        run: npm run build
