name: MyPage Build Test
on:
  push:
    branches-ignore:
      - "main"
jobs:
  check-change-existence-in-myPage:
    runs-on: ubuntu-latest
    outputs:
      has-diff-in-myPage-dir: ${{ steps.check-diff-existence-in-myPage.outputs.result }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          repository: "kikugawa-shoma/learning-sandbox"
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: test
        run: git branch && git diff main --name-only
      - name: Check Change Existence in myPage
        id: check-diff-existence-in-myPage
        run: if git diff main --name-only | grep -q myPage/ ; then echo "result=true" ; else echo "result=false" ; fi >> "$GITHUB_OUTPUT"
  echo-diff-check-result:
    runs-on: ubuntu-latest
    needs:
      - check-change-existence-in-myPage
    steps:
      - name: Echo Diff Check True Result
        if: ${{ needs.check-change-existence-in-myPage.outputs.has-diff-in-myPage-dir == 'true' }}
        run: echo "There are some changes in myPage and the build test will be executed"
      - name: Echo Diff Check False Result
        if: ${{ needs.check-change-existence-in-myPage.outputs.has-diff-in-myPage-dir == 'false' }}
        run: echo "There are no changes in myPage and the build test will not be executed"
  test-for-buildability:
    runs-on: ubuntu-latest
    needs:
      - check-change-existence-in-myPage
    if: ${{ needs.check-change-existence-in-myPage.outputs.has-diff-in-myPage-dir == 'true' }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          repository: "kikugawa-shoma/learning-sandbox"
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - uses: actions/cache@v3
        id: npm_cache
        with:
          path: myPage/node_modules
          key: ${{ hashFiles('myPage/package-lock.json') }}
      - name: Install NPM Modules
        if: steps.npm_cache.outputs.cache-hit != 'true'
        working-directory: myPage
        run: npm ci
      - name: Build Check
        working-directory: myPage
        run: npm run build
