name: build and delpoy portfolio page
on:
  push:
    branches:
      - main
    paths:
      - myPage/**
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          repository: "kikugawa-shoma/learning-sandbox"
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          path: ./pageSource
      - name: Checkout GitHub Pages Repository
        uses: actions/checkout@v4
        with:
          repository: "kikugawa-shoma/kikugawa-shoma.github.io"
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          token: ${{ secrets.SSH_PRIVATE_KEY }}
          path: ./githubPages
      - name: Build Page Source
        working-directory: pageSource/myPage
        run: npm ci && npm run build
      - name: Update My Page Static Files
        working-directory: githubPages
        run: >
          cp -rf ../pageSource/myPage/out/* ./ 
          && git config --global user.email "system@example.com"
          && git config --global user.name "System"
          && git add -A 
          && git commit -m 'update'
          && git push origin main
