name: MyPage Build Test
on:
  push:
    branches-ignore:
      - "main"
jobs:
  check-change-existence-in-myPage:
    runs-on: ubuntu-latest
    outputs:
      check-diff-existence-in-myPage: ${{ steps.check-diff-existence-in-myPage.outputs.check-diff-existence-in-myPage }}
    steps:
      - name: Check Change Existence in myPage
        run: if git diff main --name-only | grep -q myPage/ ; then echo true; else echo false; fi
        id: check-diff-existence-in-myPage
      - name: Echo Diff Check Result
        run: if [ ${{ steps.check-diff-existence-in-myPage.outputs.check-diff-existence-in-myPage }} = "true" ] ; then echo "There are changes in myPage directory"; else echo "There are no change in myPage directory"; fi
  test-for-buildability:
    runs-on: ubuntu-latest
    needs:
      - check-change-existence-in-myPage
    if: ${{ needs.check-change-existence-in-myPage.outputs.check-diff-existence-in-myPage }} == 'true'
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          repository: "kikugawa-shoma/learning-sandbox"
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: actions/cache@v3
        id: npm_cache
        with:
          path: myPage/node_modules
          key: ${{ hashFiles('myPage/package-lock.json') }}
      - name: Install NPM Modules
        if: steps.npm_cache.outputs.cache-hit != 'true'
        working-directory: myPage
        run: npm ci
      - name: Build Check
        working-directory: myPage
        run: npm run build
